services:
  - type: web
    name: home-stock-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: DATABASE_URL
        fromDatabase:
          name: home-stock-db
          property: connectionString

databases:
  - name: home-stock-db
    plan: free
    databaseName: home_stock
    user: home_stock_user
